// Um arquivo só para inserir dados no banco, para facilitar os testes.
// tem que rodar o backend para funcionar.

const API_URL = "http://localHost:3001";

const usuarios = [
  {
    nome: "Ana Clara Silva",
    email: "ana.clara@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Bruno Henrique Souza",
    email: "bruno.souza@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Camila Oliveira",
    email: "camila.oliveira@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Daniel Santos",
    email: "daniel.santos@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Eduarda Lima",
    email: "eduarda.lima@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Felipe Costa",
    email: "felipe.costa@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Gabriela Almeida",
    email: "gabriela.almeida@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Henrique Martins",
    email: "henrique.martins@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Isabela Ferreira",
    email: "isabela.ferreira@email.com",
    senha: "testeE12+",
  },
  {
    nome: "João Pedro Rocha",
    email: "joao.pedro@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Larissa Mendes",
    email: "larissa.mendes@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Lucas Ribeiro",
    email: "lucas.ribeiro@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Mariana Barbosa",
    email: "mariana.barbosa@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Rafael Nunes",
    email: "rafael.nunes@email.com",
    senha: "testeE12+",
  },
  {
    nome: "Vitória Carvalho",
    email: "vitoria.carvalho@email.com",
    senha: "testeE12+",
  },
];

let usuariosComUid = [];

async function InserirDados() {

    for(const usuario of usuarios) {
    
        const responseUsuarioAuth = await fetch(`${API_URL}/auth/registrarUsuario`, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                nome: usuario.nome,
                email: usuario.email,
                senha: usuario.senha,
            }),
        });

        const usuarioAuth = await responseUsuarioAuth.json();

        usuariosComUid.push({
            nome: usuario.nome,
            email: usuario.email,
            senha: usuario.senha,
            uid: usuarioAuth.uid,
        });
    };

    for(const usuarioDados of usuariosComUid) {

        const responseUsuario = await fetch(`${API_URL}/usuario/adicionarUsuario`, {
                method: "POST",
                headers:  {
                    "Content-Type": "application/json",
                },
                body: JSON.stringify({
                    nome: usuarioDados.nome,
                    email: usuarioDados.email,
                    uid: usuarioDados.uid,
                }),
            })
    };

    const pets = [
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[0].uid,
    dataNasc: "2025-03-07",
    descricao: "Cachorro dócil, brincalhão e muito companheiro.",
    especie: "mamiferos",
    fotoPetUrl: "/images/1.png",
    local: "São Paulo - SP",
    nome: "Thor",
    porte: "grande",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[1].uid,
    dataNasc: "2024-11-15",
    descricao: "Gata tranquila, carinhosa e acostumada com ambientes internos.",
    especie: "mamiferos",
    fotoPetUrl: "/images/2.png",
    local: "Campinas - SP",
    nome: "Luna",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[4].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[2].uid,
    dataNasc: "2023-08-21",
    descricao: "Papagaio curioso, ativo e que gosta de interação.",
    especie: "aves",
    fotoPetUrl: "/images/3.png",
    local: "Curitiba - PR",
    nome: "Louro",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[3].uid,
    dataNasc: "2022-05-10",
    descricao: "Coelho calmo, sociável e ideal para famílias.",
    especie: "mamiferos",
    fotoPetUrl: "/images/4.png",
    local: "Belo Horizonte - MG",
    nome: "Nino",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[7].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[4].uid,
    dataNasc: "2024-02-18",
    descricao: "Tartaruga tranquila, saudável e de fácil cuidado.",
    especie: "repteis",
    fotoPetUrl: "/images/5.png",
    local: "Rio de Janeiro - RJ",
    nome: "Shelly",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[5].uid,
    dataNasc: "2025-01-03",
    descricao: "Peixe colorido, ativo e acostumado com aquário comunitário.",
    especie: "peixes",
    fotoPetUrl: "/images/6.png",
    local: "Santos - SP",
    nome: "Bolha",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[2].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[6].uid,
    dataNasc: "2023-12-09",
    descricao: "Iguana saudável, calma e acostumada ao manuseio.",
    especie: "repteis",
    fotoPetUrl: "/images/7.png",
    local: "Florianópolis - SC",
    nome: "Spike",
    porte: "medio",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[7].uid,
    dataNasc: "2022-09-30",
    descricao: "Cachorra protetora, obediente e muito afetuosa.",
    especie: "mamiferos",
    fotoPetUrl: "/images/8.png",
    local: "Porto Alegre - RS",
    nome: "Mel",
    porte: "medio",
    status: "adotado",
    novoDono: usuariosComUid[1].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[8].uid,
    dataNasc: "2024-07-12",
    descricao: "Calopsita alegre, comunicativa e acostumada com pessoas.",
    especie: "aves",
    fotoPetUrl: "/images/9.png",
    local: "Salvador - BA",
    nome: "Pipoca",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[0].uid,
    dataNasc: "2021-04-25",
    descricao: "Gato independente, limpo e muito observador.",
    especie: "mamiferos",
    fotoPetUrl: "/images/1.png",
    local: "Recife - PE",
    nome: "Simba",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[5].uid,
  },

  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[1].uid,
    dataNasc: "2025-06-01",
    descricao: "Filhote brincalhão, cheio de energia e muito esperto.",
    especie: "mamiferos",
    fotoPetUrl: "/images/2.png",
    local: "Fortaleza - CE",
    nome: "Toby",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[2].uid,
    dataNasc: "2023-10-14",
    descricao: "Rã pequena, saudável e adaptada a terrário úmido.",
    especie: "anfibios",
    fotoPetUrl: "/images/3.png",
    local: "Manaus - AM",
    nome: "Verde",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[6].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[3].uid,
    dataNasc: "2024-03-20",
    descricao: "Hamster ativo, curioso e acostumado com gaiola espaçosa.",
    especie: "mamiferos",
    fotoPetUrl: "/images/4.png",
    local: "Goiânia - GO",
    nome: "Cookie",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[4].uid,
    dataNasc: "2020-12-11",
    descricao: "Cobra tranquila, saudável e indicada para tutor experiente.",
    especie: "repteis",
    fotoPetUrl: "/images/5.png",
    local: "Brasília - DF",
    nome: "Jade",
    porte: "medio",
    status: "adotado",
    novoDono: usuariosComUid[8].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[5].uid,
    dataNasc: "2025-02-08",
    descricao: "Peixe betta bonito, ativo e de fácil adaptação.",
    especie: "peixes",
    fotoPetUrl: "/images/6.png",
    local: "Natal - RN",
    nome: "Azul",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[6].uid,
    dataNasc: "2024-09-17",
    descricao: "Aranha dócil para observação, ideal para terrário adequado.",
    especie: "invertebrados",
    fotoPetUrl: "/images/7.png",
    local: "João Pessoa - PB",
    nome: "Teia",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[0].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[7].uid,
    dataNasc: "2022-01-29",
    descricao: "Cachorro calmo, obediente e ótimo para companhia.",
    especie: "mamiferos",
    fotoPetUrl: "/images/8.png",
    local: "Vitória - ES",
    nome: "Bob",
    porte: "medio",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[8].uid,
    dataNasc: "2021-07-05",
    descricao: "Gata carinhosa, castrada e acostumada com outros animais.",
    especie: "mamiferos",
    fotoPetUrl: "/images/9.png",
    local: "Maceió - AL",
    nome: "Mia",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[3].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[0].uid,
    dataNasc: "2023-06-23",
    descricao: "Canário saudável, canta bastante e gosta de ambiente iluminado.",
    especie: "aves",
    fotoPetUrl: "/images/1.png",
    local: "Aracaju - SE",
    nome: "Sol",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[1].uid,
    dataNasc: "2024-04-16",
    descricao: "Lagarto tranquilo, ativo e acostumado com terrário aquecido.",
    especie: "repteis",
    fotoPetUrl: "/images/2.png",
    local: "Belém - PA",
    nome: "Rango",
    porte: "medio",
    status: "adotado",
    novoDono: usuariosComUid[7].uid,
  },

  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[2].uid,
    dataNasc: "2025-05-12",
    descricao: "Cachorrinha dócil, muito brincalhona e sociável.",
    especie: "mamiferos",
    fotoPetUrl: "/images/3.png",
    local: "São Luís - MA",
    nome: "Amora",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[3].uid,
    dataNasc: "2022-08-19",
    descricao: "Peixe ornamental tranquilo e adaptado a aquário médio.",
    especie: "peixes",
    fotoPetUrl: "/images/4.png",
    local: "Teresina - PI",
    nome: "Nemo",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[6].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[4].uid,
    dataNasc: "2023-11-02",
    descricao: "Porquinho-da-índia manso, saudável e muito sociável.",
    especie: "mamiferos",
    fotoPetUrl: "/images/5.png",
    local: "Cuiabá - MT",
    nome: "Tico",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[5].uid,
    dataNasc: "2020-03-28",
    descricao: "Tartaruga adulta, tranquila e acostumada com espaço externo.",
    especie: "repteis",
    fotoPetUrl: "/images/6.png",
    local: "Campo Grande - MS",
    nome: "Cascão",
    porte: "medio",
    status: "adotado",
    novoDono: usuariosComUid[2].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[6].uid,
    dataNasc: "2024-10-07",
    descricao: "Periquito ativo, bonito e acostumado com viveiro.",
    especie: "aves",
    fotoPetUrl: "/images/7.png",
    local: "Palmas - TO",
    nome: "Kiwi",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[7].uid,
    dataNasc: "2023-01-13",
    descricao: "Sapo pequeno, saudável e indicado para ambiente controlado.",
    especie: "anfibios",
    fotoPetUrl: "/images/8.png",
    local: "Boa Vista - RR",
    nome: "Pingo",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[5].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[8].uid,
    dataNasc: "2021-09-09",
    descricao: "Cachorro de grande porte, leal e bastante protetor.",
    especie: "mamiferos",
    fotoPetUrl: "/images/9.png",
    local: "Porto Velho - RO",
    nome: "Max",
    porte: "grande",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[0].uid,
    dataNasc: "2022-06-30",
    descricao: "Gato brincalhão, esperto e acostumado com crianças.",
    especie: "mamiferos",
    fotoPetUrl: "/images/1.png",
    local: "Macapá - AP",
    nome: "Oliver",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[8].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[1].uid,
    dataNasc: "2024-12-25",
    descricao: "Caramujo de aquário, útil para limpeza e fácil manutenção.",
    especie: "invertebrados",
    fotoPetUrl: "/images/2.png",
    local: "Rio Branco - AC",
    nome: "Lento",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[2].uid,
    dataNasc: "2023-04-03",
    descricao: "Pato jovem, ativo e ideal para espaço aberto seguro.",
    especie: "aves",
    fotoPetUrl: "/images/3.png",
    local: "Joinville - SC",
    nome: "Quack",
    porte: "medio",
    status: "adotado",
    novoDono: usuariosComUid[4].uid,
  },

  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[3].uid,
    dataNasc: "2025-01-19",
    descricao: "Filhote de gato curioso, carinhoso e muito brincalhão.",
    especie: "mamiferos",
    fotoPetUrl: "/images/4.png",
    local: "Londrina - PR",
    nome: "Tom",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[4].uid,
    dataNasc: "2020-10-22",
    descricao: "Jabuti saudável, calmo e acostumado com quintal seguro.",
    especie: "repteis",
    fotoPetUrl: "/images/5.png",
    local: "Ribeirão Preto - SP",
    nome: "Tuga",
    porte: "medio",
    status: "adotado",
    novoDono: usuariosComUid[1].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[5].uid,
    dataNasc: "2024-08-01",
    descricao: "Peixe dourado tranquilo, bonito e de fácil cuidado.",
    especie: "peixes",
    fotoPetUrl: "/images/6.png",
    local: "Niterói - RJ",
    nome: "Gold",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[6].uid,
    dataNasc: "2023-02-14",
    descricao: "Furão esperto, ativo e precisa de bastante enriquecimento.",
    especie: "mamiferos",
    fotoPetUrl: "/images/7.png",
    local: "Uberlândia - MG",
    nome: "Zig",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[0].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[7].uid,
    dataNasc: "2022-11-27",
    descricao: "Arara jovem, inteligente e precisa de tutor dedicado.",
    especie: "aves",
    fotoPetUrl: "/images/8.png",
    local: "Sorocaba - SP",
    nome: "Aurora",
    porte: "medio",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[8].uid,
    dataNasc: "2021-05-18",
    descricao: "Lagartixa tranquila, saudável e adaptada a terrário pequeno.",
    especie: "repteis",
    fotoPetUrl: "/images/9.png",
    local: "Maringá - PR",
    nome: "Liz",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[3].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[0].uid,
    dataNasc: "2025-03-30",
    descricao: "Cachorro jovem, carinhoso e cheio de energia.",
    especie: "mamiferos",
    fotoPetUrl: "/images/1.png",
    local: "Jundiaí - SP",
    nome: "Bolt",
    porte: "medio",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[1].uid,
    dataNasc: "2023-09-06",
    descricao: "Sapo de pequeno porte, saudável e ideal para terrário úmido.",
    especie: "anfibios",
    fotoPetUrl: "/images/2.png",
    local: "Blumenau - SC",
    nome: "Brejo",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[6].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[2].uid,
    dataNasc: "2024-01-24",
    descricao: "Caranguejo pequeno, ativo e indicado para aquaterrário.",
    especie: "invertebrados",
    fotoPetUrl: "/images/3.png",
    local: "Guarulhos - SP",
    nome: "Pinça",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[3].uid,
    dataNasc: "2022-07-17",
    descricao: "Cadela dócil, companheira e acostumada a passeios.",
    especie: "mamiferos",
    fotoPetUrl: "/images/4.png",
    local: "Osasco - SP",
    nome: "Nina",
    porte: "medio",
    status: "adotado",
    novoDono: usuariosComUid[8].uid,
  },

  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[4].uid,
    dataNasc: "2025-04-04",
    descricao: "Gatinha filhote, brincalhona e muito carinhosa.",
    especie: "mamiferos",
    fotoPetUrl: "/images/5.png",
    local: "Santo André - SP",
    nome: "Lili",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[5].uid,
    dataNasc: "2020-01-09",
    descricao: "Papagaio adulto, comunicativo e acostumado com rotina.",
    especie: "aves",
    fotoPetUrl: "/images/6.png",
    local: "São Bernardo do Campo - SP",
    nome: "Zeca",
    porte: "medio",
    status: "adotado",
    novoDono: usuariosComUid[2].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[6].uid,
    dataNasc: "2023-03-11",
    descricao: "Peixe pequeno, resistente e ótimo para aquário comunitário.",
    especie: "peixes",
    fotoPetUrl: "/images/7.png",
    local: "Diadema - SP",
    nome: "Flash",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[7].uid,
    dataNasc: "2021-12-02",
    descricao: "Cobra de pequeno porte, calma e saudável.",
    especie: "repteis",
    fotoPetUrl: "/images/8.png",
    local: "Contagem - MG",
    nome: "Sombra",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[5].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[8].uid,
    dataNasc: "2024-06-15",
    descricao: "Coelho jovem, dócil e acostumado com contato humano.",
    especie: "mamiferos",
    fotoPetUrl: "/images/9.png",
    local: "Betim - MG",
    nome: "Flock",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[0].uid,
    dataNasc: "2022-10-08",
    descricao: "Galinha mansa, saudável e ideal para espaço aberto.",
    especie: "aves",
    fotoPetUrl: "/images/1.png",
    local: "Anápolis - GO",
    nome: "Clara",
    porte: "medio",
    status: "adotado",
    novoDono: usuariosComUid[4].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[1].uid,
    dataNasc: "2023-05-26",
    descricao: "Tritão pequeno, saudável e indicado para aquaterrário.",
    especie: "anfibios",
    fotoPetUrl: "/images/2.png",
    local: "Feira de Santana - BA",
    nome: "Triton",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[2].uid,
    dataNasc: "2021-08-13",
    descricao: "Cachorro grande, calmo e muito leal ao tutor.",
    especie: "mamiferos",
    fotoPetUrl: "/images/3.png",
    local: "Caxias do Sul - RS",
    nome: "Rex",
    porte: "grande",
    status: "adotado",
    novoDono: usuariosComUid[7].uid,
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[3].uid,
    dataNasc: "2024-12-03",
    descricao: "Besouro pequeno, interessante para observação em terrário.",
    especie: "invertebrados",
    fotoPetUrl: "/images/4.png",
    local: "Petrolina - PE",
    nome: "Atlas",
    porte: "pequeno",
    status: "disponivel",
  },
  {
    adicionadoEm: new Date(),
    antigoDono: usuariosComUid[4].uid,
    dataNasc: "2025-02-22",
    descricao: "Filhote dócil, curioso e ótimo para companhia.",
    especie: "mamiferos",
    fotoPetUrl: "/images/5.png",
    local: "Piracicaba - SP",
    nome: "Bento",
    porte: "pequeno",
    status: "adotado",
    novoDono: usuariosComUid[0].uid,
  },
];
    
    for(const dadosPet of pets) {
    const responseBackEnd = await fetch(`${API_URL}/pets/adicionarPet`, {
            method: "POST",
            headers:  {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({
                dadosPet: dadosPet
            }),
        })
}; 
}

InserirDados();